[project]
org-name= "ballerina"
version= "1.0.1"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/ballerina-platform/module-mongodb"

[dependencies]

[platform]
target = "java8"

    [[platform.libraries]]
    module = "mongodb"
    path = "../mongo-utils/target/mongo-utils-1.0.1.jar"
    artafactId = "mongo-utils"
    version = "1.0.1"
    groupId = "org.wso2.ei"
