[package]
org = "ballerinax"
name = "mongodb"
version = "2.1.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["MongoDB", "NoSQL"]
repository = "https://github.com/ballerina-platform/module-ballerinax-mongodb"

[[platform.java11.dependency]]
path = "../mongodb-native/build/libs/mongodb-native-2.1.0-all.jar"
groupId = "org.ballerinalang"
artifactId = "mongodb-native"
version = "2.1.0"
